In [1]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [2]:
torch.mul(x, y)

tensor([10.,  3.])

In [3]:
x.mul(y)

tensor([10.,  3.])

In [5]:
x.matmul(y.T)

tensor(13.)

In [7]:
x = torch.zeros([2, 5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [8]:
print(x.shape)

torch.Size([2, 5])


In [10]:
y = torch.rand([2,5])
print(y)

tensor([[0.4533, 0.3839, 0.3989, 0.4912, 0.4995],
        [0.8710, 0.4444, 0.8190, 0.2809, 0.0912]])


In [11]:
y.view([1,10])

tensor([[0.4533, 0.3839, 0.3989, 0.4912, 0.4995, 0.8710, 0.4444, 0.8190, 0.2809,
         0.0912]])

In [12]:
y

tensor([[0.4533, 0.3839, 0.3989, 0.4912, 0.4995],
        [0.8710, 0.4444, 0.8190, 0.2809, 0.0912]])