## PYTORCH

Python-based scientific computing package targeted as two sets of audiences:
* A replacement for NumPy to use the power of GPUs
* a deep learning research platform that provides maximum flexibility and speed

### What is pytorch

In [1]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[                   0.0000,                    0.0000,
                            0.0000],
        [                   0.0000,                    0.0000,
                            0.0000],
        [                   0.0000,                    0.0000,
                            0.0000],
        [                   0.0000,                    0.0000,
                            0.0000],
        [                   0.0000,                    0.0000,
         -2695081670318489600.0000]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5996, 0.8820, 0.5256],
        [0.1149, 0.9491, 0.9303],
        [0.2080, 0.5047, 0.8065],
        [0.0575, 0.6404, 0.0983],
        [0.3268, 0.0971, 0.8453]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.9894,  0.0707, -1.3522],
        [ 0.6424, -0.5571,  0.2762],
        [-0.6233,  1.9076,  1.3021],
        [ 0.8920, -0.2349,  0.9154],
        [ 0.3081, -1.2371, -0.0365]])


In [13]:
print(x.size())

torch.Size([5, 3])


In [14]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.9308,  1.0465, -0.9157],
        [ 1.4635, -0.4093,  0.5751],
        [ 0.2327,  2.1478,  1.7736],
        [ 0.9724, -0.0874,  1.2825],
        [ 0.7653, -0.9394,  0.4411]])


In [15]:
print(torch.add(x, y))

tensor([[-0.9308,  1.0465, -0.9157],
        [ 1.4635, -0.4093,  0.5751],
        [ 0.2327,  2.1478,  1.7736],
        [ 0.9724, -0.0874,  1.2825],
        [ 0.7653, -0.9394,  0.4411]])


In [16]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.9308,  1.0465, -0.9157],
        [ 1.4635, -0.4093,  0.5751],
        [ 0.2327,  2.1478,  1.7736],
        [ 0.9724, -0.0874,  1.2825],
        [ 0.7653, -0.9394,  0.4411]])


In [17]:
y.add_(x)
print(y)

tensor([[-0.9308,  1.0465, -0.9157],
        [ 1.4635, -0.4093,  0.5751],
        [ 0.2327,  2.1478,  1.7736],
        [ 0.9724, -0.0874,  1.2825],
        [ 0.7653, -0.9394,  0.4411]])


In [18]:
print(x[:, 1])

tensor([ 0.0707, -0.5571,  1.9076, -0.2349, -1.2371])


In [19]:
print(x)

tensor([[-0.9894,  0.0707, -1.3522],
        [ 0.6424, -0.5571,  0.2762],
        [-0.6233,  1.9076,  1.3021],
        [ 0.8920, -0.2349,  0.9154],
        [ 0.3081, -1.2371, -0.0365]])


In [21]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size() )

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [22]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.2813])
-1.2813208103179932


In [25]:
x = torch.randn(4, 4)
print(x)
print(x[2][3].item())

tensor([[-0.7608,  0.5257, -0.5432, -1.1073],
        [-0.9850,  1.7678,  0.4446,  1.0364],
        [ 1.0422,  1.0269, -0.0124, -0.1395],
        [-2.3807,  0.6095, -1.6226,  1.1405]])
-0.13954129815101624


**NumPy Bridge**

In [26]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [27]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [28]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [29]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [31]:
a += 1

In [32]:
print(a)
print(b)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [33]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    x = x+y
    print(x)
    print(x.to("cpu", torch.double))

In [ ]:
# tensor([2.4996], device='cuda:0')
# tensor([2.4996], dtype=torch.float64)

### AUTOGRAD: AUTOMATIC DIFFERENTIATION

In [34]:
import torch

In [35]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [36]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [37]:
print(y.grad_fn)

In [38]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [42]:
a = torch.randn(2, 2)
print((a*3))
print(a-1)
a = ((a*3) / (a-1))
print(a)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

tensor([[-3.0422,  0.6135],
        [-1.9935, -1.5795]])
tensor([[-2.0141, -0.7955],
        [-1.6645, -1.5265]])
tensor([[ 1.5105, -0.7712],
        [ 1.1977,  1.0347]])
False
True


In [43]:
out.backward()

In [44]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [45]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)